apiVersion: v1
kind: Service
metadata:
  name: json-server
  namespace: json-server
spec:
  selector:
    app: json-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
